"""f

Revision ID: 50c62650aca5
Revises: f9383b2f86b9
Create Date: 2024-07-21 00:09:34.568750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c62650aca5'
down_revision: Union[str, None] = 'f9383b2f86b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('value', sa.String(), nullable=False))
    op.drop_column('attribute', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('attribute', 'value')
    # ### end Alembic commands ###
