"""orders

Revision ID: 9258b5ca443d
Revises: d1f2afd1b5c0
Create Date: 2024-07-23 22:23:08.533370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9258b5ca443d'
down_revision: Union[str, None] = 'd1f2afd1b5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('order', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('order', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('order', sa.Column('address', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'address')
    op.drop_column('order', 'city')
    op.drop_column('order', 'country')
    op.drop_column('order', 'phone_number')
    # ### end Alembic commands ###
