"""f

Revision ID: f9383b2f86b9
Revises: f7f020642bbb
Create Date: 2024-07-21 00:08:28.594661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9383b2f86b9'
down_revision: Union[str, None] = 'f7f020642bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('attribute', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('attribute', 'description')
    # ### end Alembic commands ###
